In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import tensorflow as tf

In [2]:
tf.__version__

'2.4.1'

dataset = pd.read_excel("Folds5x2_pp.xlsx")
dataset.head()

In [8]:
dataset = pd.read_excel("Folds5x2_pp.xlsx")
dataset.head()

AT      V       AP     RH      PE
0  14.96  41.76  1024.07  73.17  463.26
1  25.18  62.96  1020.04  59.08  444.37
2   5.11  39.40  1012.16  92.14  488.56
3  20.86  57.32  1010.24  76.64  446.48
4  10.82  37.50  1009.23  96.62  473.90

In [9]:
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [10]:
print(X)

[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 ...
 [  31.32   74.33 1012.92   36.48]
 [  24.48   69.45 1013.86   62.39]
 [  21.6    62.52 1017.23   67.87]]


In [11]:
print(y)

[463.26 444.37 488.56 ... 429.57 435.74 453.28]


In [12]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 3)

In [13]:
print(X_train)

[[  31.54   77.24 1008.23   70.19]
 [  24.02   70.94 1008.     79.55]
 [   9.6    41.03 1021.01   69.03]
 ...
 [   6.14   39.4  1011.21   90.87]
 [  14.33   38.73 1003.52   85.92]
 [   9.73   41.01 1021.76   97.71]]


In [14]:
print(X_test)

[[  27.82   79.74 1008.37   69.46]
 [  29.01   66.44 1011.21   71.56]
 [  20.61   63.86 1015.43   73.86]
 ...
 [  18.98   60.1  1010.09   85.34]
 [  32.07   70.94 1006.91   49.9 ]
 [  14.91   40.73 1017.44   86.91]]


In [15]:
ann = tf.keras.models.Sequential()

In [16]:
%config Completer.use_jedi = False

In [17]:
ann.add(tf.keras.layers.Dense(units=6, activation= 'relu'))

In [18]:
ann.add(tf.keras.layers.Dense(units=6, activation= 'relu'))

In [19]:
ann.add(tf.keras.layers.Dense(units=1))

In [20]:
ann.compile(optimizer= 'adam', loss= 'mean_squared_error')

In [21]:
ann.fit(X_train, y_train, batch_size= 32, epochs= 100)

Epoch 1/100
240/240 [==============================] - 1s 1ms/step - loss: 278927.1230
Epoch 2/100
240/240 [==============================] - 0s 1ms/step - loss: 23924.6256
Epoch 3/100
240/240 [==============================] - 0s 1ms/step - loss: 163.6192
Epoch 4/100
240/240 [==============================] - 0s 1ms/step - loss: 116.4188
Epoch 5/100
240/240 [==============================] - 0s 1ms/step - loss: 79.6273
Epoch 6/100
240/240 [==============================] - 0s 1ms/step - loss: 74.3644: 0s - loss: 74.54
Epoch 7/100
240/240 [==============================] - 0s 1ms/step - loss: 69.0470
Epoch 8/100
240/240 [==============================] - 0s 1ms/step - loss: 68.5156: 0s - loss: 68.62
Epoch 9/100
240/240 [==============================] - 0s 1ms/step - loss: 65.1052
Epoch 10/100
240/240 [==============================] - 0s 2ms/step - loss: 65.5766
Epoch 11/100
240/240 [==============================] - 0s 2ms/step - loss: 62.4779: 0s - los
Epoch 12/100
240/240 [========

240/240 [==============================] - 0s 1ms/step - loss: 26.3143
Epoch 97/100
240/240 [==============================] - 0s 2ms/step - loss: 28.3781
Epoch 98/100
240/240 [==============================] - 0s 1ms/step - loss: 27.2588
Epoch 99/100
240/240 [==============================] - 0s 1ms/step - loss: 27.6011
Epoch 100/100
240/240 [==============================] - 0s 1ms/step - loss: 27.7263


In [22]:
y_pred = ann.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[431.14 436.48]
 [434.13 430.61]
 [450.69 446.34]
 ...
 [450.6  453.37]
 [427.84 432.33]
 [466.36 458.99]]


In [24]:
from sklearn.metrics import r2_score
print(r2_score(y_test, y_pred))

0.9111551011016958
